apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    template.openshift.io/expose-uri: http://{.spec.host}{.spec.path}
  name: grouper
spec:
  path: /grouper
  to:
    kind: Service
    name: grouper
  port:
    targetPort: 8080
