apiVersion: v1
kind: Service
metadata:
  name: grouper
  labels:
    name: grouper
spec:
  ports:
  - name: grouper
    nodePort: 0
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: grouper
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
